export enum Room {
  Outside = 'outside',
  Hallway = 'hallway',
  DiningRoom = 'diningRoom',
  LivingRoom = 'livingRoom',
  SittingRoom = 'sittingRoom',
  Conservatory = 'conservatory',
  Kitchen = 'kitchen',
  Basement = 'basement',
  GardenShed = 'gardenShed',
  BedroomGemmeker = 'bedroomGemmeker',
  BedroomObreen = 'bedroomObreen',
  Guestroom1 = 'guestroom1',
  Guestroom2 = 'guestroom2',
  BedroomHassel = 'bedroomHassel',
  Bathroom = 'bathroom',
  Attic = 'attic',
}
